In [11]:
from keras.layers import Input, Dense, Flatten, Convolution1D
from keras.layers import Concatenate, Activation, Lambda, Subtract, Dot, Multiply
from keras.models import Model, Sequential
from keras.layers import multiply
from keras.initializers import Zeros
from keras.applications.vgg19 import VGG19
from keras.engine.topology import Layer
from keras.activations import softmax
from keras import backend as K
import sys, glob, math, os
import cv2
import numpy as np
import re

input_size = [5, 10]
input_size1 = [3, 3, 4]
input_size2 = [3]

In [12]:
def custom_softmax(x):
    y = softmax(x, axis=2)
    return y

In [19]:
def custom_mult(x):
    z = multiply(x)
    return z

In [ ]:
def custom_mult2(x):
    
    
    
    return z

In [20]:
def test_model():
    inputs = Input(input_size)
    
    #out = MySoftmax()(inputs)
    
    #out = Lambda(antirectifier, output_shape=antirectifier_output_shape)(inputs)
    out = Lambda(custom_softmax)(inputs)
    
    model = Model(inputs=inputs, outputs=out)
    
    model.summary()
 
    return model
#END vgg19_lower_model()

In [21]:
def test_model_2inputs():
    x = Input(input_size, name='x')
    c = Input(input_size, name='c')
    
    y = Subtract()([x,c])
    z = Multiply()([x,y])
    
    model = Model(inputs=[x,c], outputs=z)
    
    return model
    

In [22]:
def test_model_2inputs2():
    x = Input(input_size, name='x')
    c = Input(input_size, name='c')
    
#    y = Subtract()([x,c])
#    z = Multiply()([x,y])
    z = Lambda(custom_mult)([x,c])
    
    model = Model(inputs=[x,c], outputs=z)
    
    return model

In [23]:
from numpy.random import *

#data = rand(32,5,10)
data = 0.5*np.ones((32,5,10))
data2 = 0.8*np.ones((32,5,10))


In [24]:
#model = test_model()
#pred = model.predict(data, batch_size=32, verbose=1)

model = test_model_2inputs2()
pred = model.predict([data,data2], batch_size=32, verbose=1)


32/32 [==============================] - 0s


In [25]:
print(data[0])
print(data2[0])
print(pred[0])

[[ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]
 [ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]
 [ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]
 [ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]
 [ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]]
[[ 0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8]
 [ 0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8]
 [ 0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8]
 [ 0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8]
 [ 0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8]]
[[ 0.40000001  0.40000001  0.40000001  0.40000001  0.40000001  0.40000001
   0.40000001  0.40000001  0.40000001  0.40000001]
 [ 0.40000001  0.40000001  0.40000001  0.40000001  0.40000001  0.40000001
   0.40000001  0.40000001  0.40000001  0.40000001]
 [ 0.40000001  0.40000001  0.40000001  0.40000001  0.40000001  0.40000001
   0.40000001  0.40000001  0.40000001  0.40000001]
 [ 0.40000001  0.40000001  0.40000001  0.40000001  0.40000001  0.40000001
   0.40000001  0.40